### ISSUE TITLE
Build fails if `ninja` is not installed

### ISSUE THREAD

**Issue by UndeadKernel** [tklab-tud/ID2T#89]
The build script fails if `ninja` is not available.
The script should treat `ninja` as a dependency and install it when not available.

**Comment by pepper-jk** [comment]
Ninja is not a dependency, since make is more widely used.

If you get the following error:

```
CMake Error at CMakeLists.txt:4 (project):
  Running

   '/usr/bin/ninja' '--version'

  failed with:

   No such file or directory


-- Configuring incomplete, errors occurred!
```

use `./build.sh --full` to rerun cmake. Then the build script should just use make.
