### ISSUE TITLE
DDoS: when specifying one attacker, many MAC addresses are generated

### ISSUE THREAD

**Issue by UndeadKernel** [tklab-tud/ID2T#90]
When injecting a DDoS attack with only one source (and when the source IP is provided by the user), ID2T creates a list of source MAC addresses (as seen in the labels file).

I'm not sure what are these MAC addresses used for. If only one is used, then its not intuitive that ID2T is generating more than the number specified by the parameter 'attackers.count=1'.

**Comment by pepper-jk** [comment]
Fixed with f17975639720217e001fb36cce529505f239b5d2.
